encode.go
encode_compile.go
encode_opcode.go
encode_test.go
encode_vm.go

Support VirtualMachine for encoding

---

benchmarks/go.mod
benchmarks/go.sum

Remove unused module on the benchmark.

benchmark: remove unused module

---

decode_slice.go

```bash
GOMAXPROCS=2 go test -bench Decode_MediumStruct_GoJson
```
When executed the above command, I got  the following error .
```
runtime: pointer 0xc000452010 to unused region of span span.base()=0xc0001da000 span.limit=0xc0001ddf00 span.state=1
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
```
This PR resolve this problem 🎉

Fix a bug that crashes in parallel execution

---

benchmarks/decode_test.go
decode.go
decode_array.go
decode_bool.go
decode_compile.go
decode_context.go
decode_float.go
decode_int.go
decode_interface.go
decode_map.go
decode_ptr.go
decode_slice.go
decode_stream.go
decode_string.go
decode_struct.go
decode_test.go
decode_uint.go
decode_unmarshal_json.go
decode_unmarshal_text.go
json.go

Support stream decoding

---

decode_string.go
decode_test.go

Fix null in string type

---

decode_array.go
decode_map.go
decode_slice.go
decode_test.go
helper_test.go

resolve #7 
Fix `slice` , `array` `map`  types

Fix handling of null value for some types

---

decode_map.go
decode_test.go

fix https://github.com/goccy/go-json/issues/8

Fix handling of end character in map

---

encode_compile.go
encode_opcode.go
encode_test.go
encode_vm.go

resolve #11 
Also, fix field of map type in struct .

Fix encoding of struct field after omitempty field

---

decode.go
decode_interface.go
decode_map.go
decode_number.go
decode_stream.go
decode_test.go
json.go

Support json.Number

---

json.go

Support RawMessage

---

decode.go
decode_array.go
decode_bool.go
decode_float.go
decode_int.go
decode_interface.go
decode_map.go
decode_number.go
decode_ptr.go
decode_slice.go
decode_string.go
decode_struct.go
decode_test.go
decode_uint.go
decode_unmarshal_json.go
decode_unmarshal_text.go

Support DisallowUnknownFields

---

README.md
decode_float.go
decode_map.go
decode_slice.go
encode_compile.go
encode_opcode.go
encode_vm.go
json.go
json_test.go

Add Compact/Indent/HTMLEscape/Valid

---

encode.go
encode_compile.go
encode_opcode.go
encode_test.go
encode_vm.go

Fix recursive type definition

---

decode.go
decode_array.go
decode_bool.go
decode_float.go
decode_int.go
decode_interface.go
decode_map.go
decode_number.go
decode_ptr.go
decode_slice.go
decode_stream.go
decode_string.go
decode_struct.go
decode_uint.go
decode_unmarshal_json.go
decode_unmarshal_text.go

Fix implementation of DisallowUnknownFields for improvement performance

---

compact.go
decode_bool.go
decode_interface.go
decode_map.go
decode_stream.go
encode_vm.go
export_test.go
indent.go
json.go
json_test.go

Add test cases for `json.Compact` and `json.Indent` and fix them .

Fix Compact/Indent

---

encode_compile.go

Fix unnecessary recursive operation

---

encode.go

Directly access encoder pool .

Improve encoder performance ( remove unnecessary reference )

---

compact.go
encode_compile.go
encode_test.go
encode_vm.go
json.go
rtype.go

Fix `MarshalJSON` and `MarshalText` .

Fix Marshaler

---

cmd/generator/main.go
encode_compile.go
encode_optype.go
encode_test.go
encode_vm.go

`encoding/json` encodes `[]byte` type to base64 encoded string .

Support encoding of []byte type

---

encode_compile.go
encode_test.go
encode_vm.go

FYI: https://github.com/golang/go/pull/33700

Fix map key by UnmarshalText

---

encode_compile.go
encode_test.go

Fix []byte type of implemeting Marshaler

---

encode_compile.go
encode_test.go

Fix encoding of primitive pointer with string tag

---

encode.go
encode_opcode.go
encode_test.go
encode_vm.go

Fix cycle pointer value

---

encode_test.go
json.go

Fix encoding of json.Number

---

cmd/generator/main.go
encode_compile.go
encode_optype.go
encode_test.go
encode_vm.go

Fix processing of omitempty tag

---

decode_float.go
decode_interface.go
decode_test.go
json_test.go
number_test.go
tagkey_test.go

Also, fix decoding from `interface{}` to `map` type .

Add test cases from encoding/json 

---

encode.go
encode_compile.go
encode_opcode.go
encode_string.go
encode_vm.go
json.go
stream_test.go
struct_field.go
tagkey_test.go

Fix stream encoding

---

cmd/generator/main.go
decode_map.go
decode_test.go
encode_compile.go
encode_optype.go
encode_vm.go
example_text_marshaling_test.go

Fix encoding of pointer fields ( primitive type )

---

cmd/generator/main.go
encode_optype.go

Format opcode

---

cmd/generator/main.go
decode_test.go
encode_compile.go
encode_opcode.go
encode_optype.go
encode_vm.go
json.go

Pass [this](https://github.com/goccy/go-json/compare/feature/fix-anonymous-fields?expand=1#diff-373fb23355f8ed601aa2d3c450033ccd8cf067b36ae6255cb9d2af857bf71f55L1732-L1772) test case

Fix recursive anonymous field

---

encode_vm.go

Fix resolve conflict to #55.
Now certainly  passes "go test -gcflags=-d=checkptr".

Fix resolve conflict to #55

---

.github/workflows/go.yml

Support multiple go version

---

.github/workflows/go.yml
encode_vm.go
json_test.go

Fix testing `TestIndentBig` with a lot of GC .

Fix a bugs where pointers are unexpectedly freed

---

encode.go

Optimize to use `atomic.LoadPointer` / `atomic.StorePointer` technique instead of `sync.Map` .

Optimize access to opcodeMap

---

benchmarks/encode_test.go
benchmarks/go.mod
benchmarks/go.sum

Add github.com/segmentio/encoding/json to benchmark

---

encode.go
encode_compile.go
encode_context.go
encode_vm.go

Refactor reuse logic of buffer .

Improve encoding performance

---

cmd/generator/main.go
encode.go
encode_compile.go
encode_context.go
encode_opcode.go
encode_vm.go

Optimize about HTML Escape processing

---

decode_float.go
stream_test.go

Fix streaming decoder for float value

---

decode_interface.go
decode_unmarshal_json.go
encode_vm.go
encode_vm_escaped.go
encode_vm_escaped_indent.go
encode_vm_indent.go

Fixed the problem that `emptyInterface` was expected and processed when `reflect.Interface` type .
Also, I fixed encoding with nil pointer value of implementing MarshalJSON .

Fix some bugs of encoder/decoder ( for #93 )

---

encode.go
json.go

Optimize copy of byte slice for encoder

---

benchmarks/encode_test.go
encode_vm.go
encode_vm_escaped.go
encode_vm_escaped_indent.go
encode_vm_indent.go
json.go

Reduce memory allocation at encoding `MarshalJSON`

Fix encoding of type which implemented MarshalJSON

---

decode_interface.go
decode_test.go

fix https://github.com/goccy/go-json/issues/98

Fix decoding of escape char at UnmarshalJSON

---

.golangci.yml
Makefile
decode_slice.go
encode_string.go

Related to https://github.com/goccy/go-json/pull/108

Fix lint error

---

encode_compile.go
encode_test.go

Fix encoding of anonymous struct

---

codec.go
decode_compile.go
decode_compile_norace.go
decode_compile_race.go
decode_interface.go
decode_ptr.go
decode_slice.go
decode_string.go
decode_test.go
encode_compile_norace.go
encode_compile_race.go

fix #119 
Type check and if it is not an empty interface, perform processing according to the type .

Fix decoding of interface{} type

---

decode_stream.go
stream_test.go

Resolves https://github.com/goccy/go-json/issues/123.

Wait for io.EOF when decoding a stream

---

decode.go
decode_compile.go
decode_compile_norace.go
decode_compile_race.go
decode_interface.go
json.go
rtype.go

- Fix error of **race detection**
- Revive noescape trick for decoder ( `UnmarshalNoEscape`  )

Remove unnecessary dependency on decoder

---

decode_interface.go
decode_test.go

fix: fails decode escaped string to empty interface

---

decode_interface.go

Fix decoding of pointer of empty interface type

---

cover_bool_test.go
cover_float32_test.go
cover_float64_test.go
cover_helper_test.go
cover_int16_test.go
cover_int32_test.go
cover_int64_test.go
cover_int8_test.go
cover_int_test.go
cover_uint16_test.go
cover_uint32_test.go
cover_uint64_test.go
cover_uint8_test.go
cover_uint_test.go
encode_vm.go
encode_vm_escaped.go
encode_vm_escaped_indent.go
encode_vm_indent.go

Also add operations for bool type to the encoder .

Add pointer-type StructField operations to the encoder

---

decode.go
decode_context.go
decode_map.go
decode_struct.go

related to https://github.com/swaggest/jsonschema-go/pull/14

Fix decoder (  mainly map type fixing )

---

decode_struct.go

Use bits.TrailingZeros for bitmap field

---

decode_compile.go
decode_string.go
decode_test.go
decode_wrapped_string.go

Fix decoding of type of null string

---

decode_ptr.go
decode_test.go

Use pre allocated pointer if exists it

---

decode_bool.go
decode_float.go
decode_int.go
decode_interface.go
decode_map.go
decode_slice.go
decode_string.go
decode_test.go
decode_uint.go
decode_unmarshal_text.go

Fix decoding of null value

---

cmd/generator/main.go
encode_optype.go

Remove int8/int16/int32/int64 and uint8/uint16/uint32/uint64 optype .

Remove unnecessary optype

---

cover_bool_test.go
cover_bytes_test.go
cover_float32_test.go
cover_float64_test.go
cover_helper_test.go
cover_int16_test.go
cover_int32_test.go
cover_int64_test.go
cover_int8_test.go
cover_int_test.go
cover_string_test.go
cover_uint16_test.go
cover_uint32_test.go
cover_uint64_test.go
cover_uint8_test.go
cover_uint_test.go
internal/encoder/compiler.go
internal/encoder/opcode.go
internal/encoder/vm/util.go
internal/encoder/vm/vm.go
internal/encoder/vm_escaped/util.go
internal/encoder/vm_escaped/vm.go
internal/encoder/vm_escaped_indent/util.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/util.go
internal/encoder/vm_indent/vm.go

Add []byte type's test case and fix encoding of primitive pointer types and []byte type .

Fix encoding of primitive pointer types and []byte type

---

internal/encoder/compiler.go

Fix bugs of nil pointer of typeAddr value

---

.github/workflows/go.yml
cover_helper_test.go
cover_number_test.go
internal/encoder/compiler.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Add test case of encoder for json.Number type

---

internal/encoder/encoder.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Fix indent number for OpMarshalJSON

---

internal/encoder/compiler.go
internal/encoder/opcode.go
internal/encoder/vm/vm.go
internal/encoder/vm_escaped/vm.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Optimize wrapped omitempty operation

---

decode.go
json.go

Use type alias for Delim/Token/RawMessage type

---

cover_slice_test.go
internal/encoder/compiler.go
internal/encoder/vm/vm.go
internal/encoder/vm_escaped/vm.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Add slice test

---

cover_marshal_json_test.go
internal/encoder/compiler.go
internal/encoder/encoder.go
internal/encoder/opcode.go
internal/encoder/vm/vm.go
internal/encoder/vm_escaped/vm.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Remove reflection based type check, and use static property of opcode

Fix encoding of MarshalJSON of function type

---

cover_map_test.go
cover_slice_test.go
internal/encoder/compiler.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Fix encoding of recursive slice/map

---

decode_interface.go

resolve #171 
Use cached decoder instance to reduce allocation number .

Improve decoder performance for empty interface type

---

encode_test.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

fix https://github.com/goccy/go-json/issues/180

Fix unnecessary indent for empty slice/array

---

decode_int.go
decode_test.go
decode_uint.go

Fix decoder for invalid number value

---

cover_bool_test.go
internal/encoder/encoder.go
internal/encoder/vm/vm.go
internal/encoder/vm_debug/vm.go
internal/encoder/vm_escaped/vm.go
internal/encoder/vm_escaped_indent/vm.go
internal/encoder/vm_indent/vm.go

Fix encoding custom types zero values with omitempty when marshaller exists

---

benchmarks/bench_test.go
internal/encoder/compact.go
internal/encoder/encoder.go
internal/encoder/indent.go
internal/encoder/vm/vm.go
internal/encoder/vm_debug/vm.go
internal/encoder/vm_escaped/vm.go
json_test.go

fix #125 
- Validate the input buffer for json.Compact / json.Indent 
- Improve performance

Fix Compact/Indent API

---

decode_context.go
decode_stream.go
decode_test.go

Fix decoding of backslash char at the end of string

---

.github/FUNDING.yml
README.md

Add sponsor section to the README

---

.github/workflows/go.yml
benchmarks/slow_reader_test.go
decode_stream.go
decode_struct.go

fix https://github.com/goccy/go-json/issues/197
Thank @DasSkelett !
I fixed #197 based on the reproduction code and information I received.

Fix stream decoder when use slow reader

---

decode_stream.go
decode_string.go

fix https://github.com/goccy/go-json/issues/214

Fix stream decoder for unicode char

---

decode_slice.go
decode_test.go

Fix decoding of slice element

---

decode_map.go
decode_stream.go
decode_string.go

fix https://github.com/goccy/go-json/issues/217

Fix calculating of length for stream decoder

---

encode_test.go
internal/encoder/compiler.go

Fix encoding of using empty interface as map key

---

internal/cmd/generator/vm.go.tmpl
internal/encoder/vm/vm.go
internal/encoder/vm_color/vm.go
internal/encoder/vm_color_indent/vm.go
internal/encoder/vm_indent/vm.go

Optimize lookup process for seen pointer

Improve encoding performance for empty interface type

---

encode_test.go
internal/cmd/generator/vm.go.tmpl
internal/encoder/vm/vm.go
internal/encoder/vm_color/vm.go
internal/encoder/vm_color_indent/vm.go
internal/encoder/vm_indent/vm.go

fix https://github.com/goccy/go-json/issues/270
This issue similar to https://github.com/goccy/go-json/pull/265

Fix encoding of embedded struct that isn't first field

---

internal/decoder/string.go
stream_test.go

fix: fixed buffer length bug on string decoder

---

encode_test.go
internal/cmd/generator/main.go
internal/encoder/optype.go

Fix operation conversion for PtrHead to Head in Recursive type

---

internal/cmd/generator/vm.go.tmpl
internal/encoder/decode_rune.go
internal/encoder/encoder.go
internal/encoder/vm/vm.go
internal/encoder/vm_color/vm.go
internal/encoder/vm_color_indent/vm.go
internal/encoder/vm_indent/vm.go

Refactor encoder

---

encode_test.go
internal/cmd/generator/vm.go.tmpl
internal/encoder/vm/vm.go
internal/encoder/vm_color/vm.go
internal/encoder/vm_color_indent/vm.go
internal/encoder/vm_indent/vm.go

fix https://github.com/goccy/go-json/issues/316

Fix MarshalIndent for interface type

---

encode_test.go
internal/cmd/generator/vm.go.tmpl
internal/encoder/vm/vm.go
internal/encoder/vm_color/vm.go
internal/encoder/vm_color_indent/vm.go
internal/encoder/vm_indent/vm.go

Fix encoding of MarshalText/MarshalJSON operation with head offset

---

decode_test.go
internal/decoder/compile.go
internal/decoder/invalid.go

fix https://github.com/goccy/go-json/issues/320

Add invalid decoder to delay type error judgment at decode

---

decode_test.go
internal/decoder/compile.go

fix https://github.com/goccy/go-json/issues/303

Fix logic of removing struct field for decoder

---

encode_test.go
internal/encoder/code.go

Fix the case where the embedded field is at the end

---

decode_test.go
internal/decoder/unmarshal_json.go

fix: panic when decoding time.Time with context

---

internal/decoder/stream.go

fix: incorrect handling on skipValue

---

decode_test.go
internal/decoder/map.go

fix: avoid reading the next character in buffer to nul consideration

---

decode_test.go
internal/decoder/int.go

fix: to care ints minimum values

---

decode_test.go
internal/decoder/stream.go

fix: mismatched between len(s.buf) and s.bufSize

---

decode_test.go
internal/decoder/string.go

fix: to care surrogate-pair on stringDecoder

---

decode_test.go
internal/decoder/compile.go
internal/encoder/code.go
internal/runtime/struct_field.go

fix: determining embedded structs was wrong

---

decode_test.go
internal/decoder/string.go

fix: add escape sequence validation

---

encode_test.go
internal/decoder/string.go

fix: forgot to update p after read

---

decode_test.go
internal/decoder/struct.go

fix: added buffer size check when decoding key

---

internal/encoder/compiler.go
test/cover/cover_slice_test.go

Fix https://github.com/goccy/go-json/issues/504

Fix custom map marshaling
