- encode.go
- encode_opcode.go
Currently, `opcode` variable is shared by multiple goroutine .
Therefore, if update state of `opcode` , it will happen race condition .
In this PR, copy opcode before running ( also, manage copying process by sync.Pool )
> Fix parallel encoding

- encode_compile.go
- encode_opcode.go
- encode_test.go
- encode_vm.go
> Fix recursive definition of struct

- encode.go
- encode_test.go
But `goccy/go-json` omit `exponent must not have leading zeros` because `json-iterator/go` doesn't support this .
> Fix encoding format for float32 and float64

- decode.go
- decode_bool.go
- decode_compile.go
- decode_interface.go
- decode_map.go
- decode_ptr.go
- decode_slice.go
- decode_string.go
- decode_unmarshal_json.go
- decode_unmarshal_text.go
- encode.go
- encode_context.go
- encode_vm.go
Most of the invalid usages due to the conversion from uintptr to
unsafe.Pointer. In general, unsafe.Pointer(p) where p of type uintptr is
considered unsafe.
To fix that, use &p instead of p, then introduce another dereference.
Example, the invalid usage:
```
*(*int)(unsafe.Pointer(p)) = int(v)
```
wil become:
```
**(**int)(unsafe.Pointer(&p)) = int(v)
```
While at it, also removing all usages of reflect.SliceHeader.
There're some problem with current usage of reflect.SliceHeader.
First, it violates the unsafe pointer conversion (rule 6th), that said,
reflect.SliceHeader must not used as plain struct.
Second, the lowest version that go-json supports, go1.12, reflect
package did not use SliceHeader in typedslicecopy, but use the safety
version. There's no reason that go-json continue using …
> Make "go test -gcflags=-d=checkptr" passes

- decode.go
- decode_array.go
- decode_bool.go
- decode_compile.go
- decode_float.go
- decode_int.go
- decode_interface.go
- decode_map.go
- decode_number.go
- decode_ptr.go
- decode_slice.go
- decode_string.go
- decode_struct.go
- decode_uint.go
- decode_unmarshal_json.go
- decode_unmarshal_text.go
- decode_wrapped_string.go
Pass `unsafe.Pointer` instead of `uintptr` to `decode()` .
So, currently `UnmarshalNoEscape` doesn't work ... ( can't reduce allocation count )
> Fix race data for decoder

- decode_array.go
- decode_slice.go
- decode_struct.go
Fix checkptr validation error on decode side.
Maybe forgot to fix it in ~https://github.com/goccy/go-json/commit/6b1d701387077a61dadc929782195a3cbd3867a9~
**EDIT**: I'm misunderstood, actually https://github.com/goccy/go-json/commit/fd7a72c0b8d127969557247fa3c8258151bb13b0
```console
$ go1.15.5 vet -unsafeptr github.com/goccy/go-json
./decode_array.go:35:46: possible misuse of unsafe.Pointer
./decode_array.go:95:50: possible misuse of unsafe.Pointer
./decode_slice.go:94:46: possible misuse of unsafe.Pointer
./decode_slice.go:195:50: possible misuse of unsafe.Pointer
./decode_struct.go:58:40: possible misuse of unsafe.Pointer
./decode_struct.go:113:44: possible misuse of unsafe.Pointer
```
> Fix checkptr validation error on decode

- encode_opcode.go
Like Go runtime, change `uintptrSize` to constant.
> Change uintptrSize to constant

- .github/workflows/go.yml
- benchmarks/encode_test.go
- encode.go
- json.go
Add `MarshalNoEscape` API to available noescape trick for argument at encoding .
So, `Marshal` 's default behavior is escape argument .
> Add noescape API for encoder

- encode.go
- encode_compile.go
- encode_context.go
- encode_vm.go
- encode_vm_escaped.go
Move almost `opStructFieldRecursive` 's runtime process to compile phase .
This improves performance and avoids destructive changes to `jmp.code` .
> Fix recursive call at concurrent execution

- benchmarks/encode_test.go
- encode.go
Use `reflect.typelinks` trick to make list of opcodeSet .
> Improve performance of lookup of opcodeSet at encoding

- .codecov.yml
- benchmarks/encode_test.go
- encode.go
- encode_compile.go
- encode_context.go
- encode_opcode.go
- encode_vm.go
- encode_vm_escaped.go
- encode_vm_escaped_indent.go
- encode_vm_indent.go
- json.go
- option.go
- Rename many Encoder's private APIs
- Strip many methods from the Encoder
- Fix error message ( https://github.com/goccy/go-json/issues/106 )
- Add `.codecov.yml` to the project's root directory.
> Refactor the encoder to fix a bug where streaming encoders can't reuse buffer

- codec.go
- decode.go
- decode_compile.go
- decode_compile_norace.go
- decode_compile_race.go
- decode_context.go
- decode_int.go
- decode_stream.go
- decode_string.go
- decode_struct.go
- encode_compile.go
Good news. In Unmarshal's benchmark, go-json is faster than gojay .
Faster 20% - 30% than master branch 
```
benchmark                                                     old ns/op     new ns/op     delta
Benchmark_Decode_SmallStruct_Unmarshal_EncodingJson-16        2547          2436          -4.36%
Benchmark_Decode_SmallStruct_Unmarshal_JsonIter-16            793           758           -4.41%
Benchmark_Decode_SmallStruct_Unmarshal_GoJay-16               461           444           -3.69%
Benchmark_Decode_SmallStruct_Unmarshal_GoJayUnsafe-16         409           405           -0.98%
Benchmark_Decode_SmallStruct_Unmarshal_SegmentioJson-16       1039          1024          -1.44%
Benchmark_Decode_SmallStruct_Unmarshal_GoJson-16              498           352           -29.32% …
```
> Dramatically improve decoder performance

- README.md
I pointed segmentio/encoding/json to `/tree/master/json`. Should it just be straight to the encoding repository root instead?
> Fix broken links to segmentio/encoding and jettison

- decode_struct.go
Remove the process of comparing `keyIdx` and `keyBitmapLen`
```
Benchmark_Decode_SmallStruct_Unmarshal_EncodingJson-16            420442              2464 ns/op             400 B/op         10 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_JsonIter-16               1570598               765 ns/op             208 B/op         13 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_GoJay-16                  2670846               462 ns/op             256 B/op          2 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_GoJayUnsafe-16            3040153               398 ns/op             112 B/op          1 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_SegmentioJson-16          1203678               993 ns/op             192 B/op          5 allocs/op …
```
> Optimize decoding of struct field

- decode_stream.go
- decode_string.go
- decode_struct.go
```
benchmark                                                     old ns/op     new ns/op     delta
Benchmark_Decode_SmallStruct_Stream_GoJson-16                 736           677           -8.02%
Benchmark_Decode_MediumStruct_Stream_GoJson-16                4094          3184          -22.23%
Benchmark_Decode_LargeStruct_Stream_GoJson-16                 56639         43953         -22.40%
```
> Optimize streaming decoder by BCE

- decode.go
- decode_anonymous_field.go
- decode_array.go
- decode_bool.go
- decode_bytes.go
- decode_compile.go
- decode_context.go
- decode_float.go
- decode_int.go
- decode_interface.go
- decode_map.go
- decode_number.go
- decode_ptr.go
- decode_slice.go
- decode_stream.go
- decode_string.go
- decode_struct.go
- decode_test.go
- decode_uint.go
- decode_unmarshal_json.go
- decode_unmarshal_text.go
- decode_wrapped_string.go
- encode_vm_escaped.go
- error.go
- stream_test.go
- Fix not being able to return `UnmarshalTypeError` when it should be returned ( `TestUnmarshalTypeError` )
- Fix decoding of prefilled value ( `TestPrefilled` )
- Fix decoding of invalid value ( `TestInvalidUnmarshal` `TestInvalidUnmarshalText` )
- Fix decoding of embedded unexported pointer field ( `TestUnmarshalEmbeddedUnexported` )
- Fix decoding of deep recursive structure ( `TestUnmarshalMaxDepth` )
> Fix decoder

- cover_int16_test.go
- cover_int32_test.go
- cover_int64_test.go
- cover_int8_test.go
- cover_int_test.go
- encode_compile.go
- encode_int.go
- encode_opcode.go
- encode_vm.go
- encode_vm_escaped.go
- encode_vm_escaped_indent.go
- encode_vm_indent.go
fix #139 
Integrate int/int8/int16/int32/int64 operation to int and also integrate uint/uint8/uint16/uint32/uint64 operation to uint .
This reduces switch-case branching on numbers by 4/5 .
All numbers are retrieved as uint64 value and then properly masked and used by bitwise operations.
Has almost no performance impact 😄 
```
$ go test -bench Encode_
goos: darwin
goarch: amd64
pkg: benchmark
Benchmark_Encode_SmallStruct_EncodingJson-16                     2218426               544 ns/op             256 B/op          2 allocs/op
Benchmark_Encode_SmallStruct_JsonIter-16                         2123742               564 ns/op             264 B/op          3 allocs/op
Benchmark_Encode_SmallStruct_EasyJson-16                         2350054               509 ns/op             720 B/op …
```
> Reduce memory usage at compile

- cover_map_test.go
- encode_compile.go
- encode_vm_escaped_indent.go
- encode_vm_indent.go
I noticed that nested map type needs to dereference .
> Fix encoding of nested map

- cover_marshal_json_test.go
- internal/encoder/compiler.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_escaped/vm.go
- internal/encoder/vm_escaped_indent/vm.go
- internal/encoder/vm_indent/vm.go
fix #151 
When processing `OpMarshalJSON` and `OpMarshalText`, if it is a pointer type and an element of `Slice` or `Array` or `Map`, it must be dereferenced and then cast.
> Fix encoding of marshaler

- internal/cmd/generator/main.go
- internal/encoder/compiler.go
- internal/encoder/opcode.go
- internal/encoder/optype.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_escaped/vm.go
- internal/encoder/vm_escaped_indent/vm.go
- internal/encoder/vm_indent/vm.go
rename from `OpStructFieldRecursive` and `OpStructFieldRecursivePtr` and `OpStructFieldRecursiveEnd` to `OpRecursive` and `OpRecursivePtr` and `OpRecursiveEnd` .
`OpRecursive` and `OpRecursivePtr` operation needs `OpStructHead` or `OpStructField` ( wrapped operation ) before itself .
> Fix recursive operation

- decode_compile.go
- decode_test.go
Enable `TestInvalidStringOption` in decode_test.go
> Fix invalid string option

- .codecov.yml
- .golangci.yml
- codecov.yaml
- encode.go
- encode_test.go
- internal/encoder/compiler.go
- internal/encoder/compiler_norace.go
- internal/encoder/compiler_race.go
- internal/encoder/encoder.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_debug/util.go
- internal/encoder/vm_debug/vm.go
- internal/encoder/vm_escaped/vm.go
- internal/encoder/vm_escaped_indent/vm.go
- option.go
Add `json.Debug()` option for `json.MarshalWithOption` .
```go
type mustErrTypeForDebug struct{}
func (mustErrTypeForDebug) MarshalJSON() ([]byte, error) {
panic("panic")
return nil, fmt.Errorf("panic")
}
func TestDebugMode(t *testing.T) {
defer func() {
if err := recover(); err == nil {
t.Fatal("expected error")
}
}()
json.MarshalWithOption(mustErrTypeForDebug{}, json.Debug())
}
```
The above code cause panic. In this case, go-json catch error and output debug information like the following:
```
=============[DEBUG]===============
* [TYPE]
json_test.mustErrTypeForDebug
* [ALL OPCODE]
[0]MarshalJSON ([idx:0])
* [CURRENT OPCODE]
&{Op:MarshalJSON Type:json_test.mustErrTypeForDebug DisplayIdx:0 Key:[] EscapedKey:[] PtrNum:0 DisplayKey: IsTaggedKey:false AnonymousKey:false AnonymousHead:false …
```
> Add debug mode

- decode_slice.go
- decode_test.go
fix https://github.com/goccy/go-json/issues/166
- https://github.com/goccy/go-json/blob/master/decode_ptr.go#L47-L53
- https://github.com/goccy/go-json/blob/master/decode_ptr.go#L82-L88
If there is a pointer value, go-json will use it. (This behavior is necessary to achieve the ability to prioritize pre-populated values). However, since slices are reused internally, there was a bug that referred to the previous pointer value.
Therefore, it is not necessary to refer to the pointer value in advance for the slice element, so it is explicitly initialized.
> Fix decoding of slice of pointer type

- cover_string_test.go
- internal/encoder/compiler.go
handling of indirect or not is so difficult...
https://github.com/goccy/go-json/issues/149#issuecomment-808385803
https://github.com/goccy/go-json/issues/149#issuecomment-809466495
This PR fixes the above link's problem .
> Fix detection of indirect field

- json.go
- json_test.go
Valid is currently inconsistent with "encoding/json" because it returns true when there is additional non-whitespace after the initial value.  This changes it to use decoder and returns false when `decoder.More()` returns true after decoding a value.
> Make Valid more consistent with "encoding/json"

- encode_test.go
- internal/encoder/compiler.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_debug/vm.go
- internal/encoder/vm_escaped/vm.go
- internal/encoder/vm_escaped_indent/vm.go
- internal/encoder/vm_indent/vm.go
> Fix encoding of omitempty feature for the slice or interface type

- decode.go
- decode_test.go
fix https://github.com/goccy/go-json/issues/176
> Fix decoding of invalid top level value

- encode.go
- internal/encoder/compact.go
- internal/encoder/context.go
- internal/encoder/encoder.go
- internal/encoder/indent.go
- internal/encoder/vm_escaped_indent/util.go
- internal/encoder/vm_escaped_indent/vm.go
- internal/encoder/vm_indent/util.go
- internal/encoder/vm_indent/vm.go
around **2x** faster than encoding/json
```
$ go test -bench Indent
goos: darwin
goarch: amd64
pkg: benchmark
Benchmark_Indent_EncodingJson-16              38          30272302 ns/op        17069782 B/op         19 allocs/op
Benchmark_Indent_GoJson-16                    80          14656825 ns/op         5169307 B/op          2 allocs/op
PASS
ok      benchmark       3.615s
$ go test -bench Compact
goos: darwin
goarch: amd64
pkg: benchmark
Benchmark_Compact_EncodingJson-16            100          10036194 ns/op         1941742 B/op          1 allocs/op
Benchmark_Compact_GoJson-16                  190           6241213 ns/op         1941677 B/op          1 allocs/op
PASS
ok      benchmark       3.088s
```
> Optimize json.Compact and json.Indent

- benchmarks/decode_test.go
- benchmarks/go.mod
- benchmarks/go.sum
I add https://github.com/valyala/fastjson to the benchmark of decoder .
Sure it was faster than `encoding/json`, but slower than any other library
```
goos: darwin
goarch: amd64
pkg: benchmark
Benchmark_Decode_SmallStruct_Unmarshal_EncodingJson-16            511214              2286 ns/op             400 B/op         10 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_FastJson-16                705026              1633 ns/op            3376 B/op         11 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_JsonIter-16               1622686               745 ns/op             208 B/op         13 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_GoJay-16                  2751475               455 ns/op             256 B/op          2 allocs/op …
```
> Add valyala/fastjson to benchmark

- decode_slice.go
- decode_test.go
fix #195 
In decoding `UnmarshalJSON`, it is assumed that the passed pointer is used as it is as a receiver. If a type that implements UnmarshalJSON is specified as an element of slice, this should be taken into consideration so that the pointer of the reused slice element is not passed as it is.
> Fix decoding of slice with type implemented UnmarshalJSON

- decode_context.go
- decode_interface.go
- decode_test.go
fix https://github.com/goccy/go-json/issues/201
> Fix decoding of null value for interface type that doesn't implement Unmarshaler

- decode_bytes.go
- decode_test.go
> Fix decoding of null value to []byte by json.Unmarshal

- decode_slice.go
- decode_test.go
```
import "encoding/json "
func TestJSONSlice(t *testing.T) {
slice := []int{}
err := json.Unmarshal([]byte(`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`), &slice)
if err != nil {
t.Fatal(err)
}
t.Log(
len(slice), // 10
cap(slice), // 13,
)
err = json.Unmarshal([]byte(`[11]`), &slice)
if err != nil {
t.Fatal(err)
}
t.Log(
len(slice), // 1
cap(slice), // 13
slice[0],   // 11
*(*int)(unsafe.Pointer((*reflect.SliceHeader)(unsafe.Pointer(&slice)).Data + 8*9)), // 10
)
}
```
> when cap is enough, reuse slice data for compatibility with encoding/json

- cover_bool_test.go
- cover_float32_test.go
- cover_float64_test.go
- cover_int_test.go
- cover_number_test.go
- cover_string_test.go
- cover_uint_test.go
- docker-compose.yml
- internal/cmd/generator/main.go
- internal/encoder/compiler.go
- internal/encoder/encoder.go
- internal/encoder/opcode.go
- internal/encoder/optype.go
- internal/encoder/vm/util.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_debug/util.go
- internal/encoder/vm_debug/vm.go
- internal/encoder/vm_escaped/util.go
- internal/encoder/vm_escaped/vm.go
- internal/encoder/vm_escaped_indent/util.go
- internal/encoder/vm_escaped_indent/vm.go
- internal/encoder/vm_indent/util.go
- internal/encoder/vm_indent/vm.go
- internal/runtime/struct_field.go
fix https://github.com/goccy/go-json/issues/191
Rename the operation created by the `string` tag from a `StringTag` .
>  Supports using omitempty and string tags at the same time

- decode_slice.go
- decode_test.go
fix https://github.com/goccy/go-json/issues/228
If the entered slice length is greater than zero, copy all references to the shared slice .
> Keep original reference of slice element

- encode.go
- internal/cmd/generator/main.go
- internal/cmd/generator/vm.go.tmpl
- internal/encoder/compiler.go
- internal/encoder/compiler_norace.go
- internal/encoder/compiler_race.go
- internal/encoder/context.go
- internal/encoder/encode_opcode_test.go
- internal/encoder/encoder.go
- internal/encoder/int.go
- internal/encoder/opcode.go
- internal/encoder/optype.go
- internal/encoder/vm/debug_vm.go
- internal/encoder/vm/util.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_escaped/debug_vm.go
- internal/encoder/vm_escaped/util.go
- internal/encoder/vm_escaped/vm.go
- internal/encoder/vm_escaped_indent/debug_vm.go
- internal/encoder/vm_escaped_indent/util.go
- internal/encoder/vm_escaped_indent/vm.go
- internal/encoder/vm_indent/debug_vm.go
- internal/encoder/vm_indent/util.go
- internal/encoder/vm_indent/vm.go
- size_test.go
Adjust memory layout of the opcode to 128 bytes in a 64-bit environment
> Fix opcode layout

- encode_test.go
- internal/encoder/opcode.go
fix #235 
I expected `Opcode.TotalLength` to return the maximum idx of the `RuntimeContext` used by the opcode, but by refactoring the opcode layout, the `Idx` property now behaves the same as the previous `HeadIdx` of opcode. 
As a result, an invalid value was returned as `TotalLength`, and as a result of trying to save the `RuntimeContext` using that value, a problem occurred.
> Fix value of totalLength for encoding

- decode_struct.go
- decode_test.go
fix https://github.com/goccy/go-json/issues/234
support escaped character contains unicode char for decoding field name of struct
> Fix decoding fields containing escaped characters

- benchmarks/decode_test.go
- decode.go
- internal/decoder/anonymous_field.go
- internal/decoder/array.go
- internal/decoder/bool.go
- internal/decoder/bytes.go
- internal/decoder/context.go
- internal/decoder/float.go
- internal/decoder/int.go
- internal/decoder/interface.go
- internal/decoder/map.go
- internal/decoder/number.go
- internal/decoder/option.go
- internal/decoder/ptr.go
- internal/decoder/slice.go
- internal/decoder/stream.go
- internal/decoder/string.go
- internal/decoder/struct.go
- internal/decoder/type.go
- internal/decoder/uint.go
- internal/decoder/unmarshal_json.go
- internal/decoder/unmarshal_text.go
- internal/decoder/wrapped_string.go
- json.go
- option.go
In the default behavior, go-json, like `encoding/json`, will reflect the result of the last evaluation when a field with the same name exists. I've added new options to allow you to change this behavior. `json.DecodeFieldPriorityFirstWin` option reflects the result of the first evaluation if a field with the same name exists. This behavior has a performance advantage as it allows the subsequent strings to be skipped if all fields have been evaluated.
Results
```
goos: darwin
goarch: amd64
pkg: benchmark
Benchmark_Decode_SmallStruct_Unmarshal_EncodingJson-16                            418848              2395 ns/op             400 B/op         10 allocs/op
Benchmark_Decode_SmallStruct_Unmarshal_FastJson-16                                720466              1624 ns/op            3376 B/op …
```
> Add DecodeFieldPriorityFirstWin option

- internal/cmd/generator/vm.go.tmpl
- internal/encoder/compiler.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/vm.go
fix #247 
fix indent number and totalLength for recursive type .
After fixed, I tried to run benchmark was introduced in #247 
```
goos: darwin
goarch: amd64
pkg: benchmark
BenchmarkMarshalIndentEncodingJson-16         24284             48370 ns/op          105041 B/op         25 allocs/op
BenchmarkMarshalIndentGoJson-16              120224              9335 ns/op           22512 B/op         22 allocs/op
```
> Fix MarshalIndent

- decode.go
- decode_test.go
- encode.go
- encode_test.go
- internal/decoder/compile.go
- internal/decoder/interface.go
- internal/decoder/option.go
- internal/decoder/struct.go
- internal/decoder/type.go
- internal/decoder/unmarshal_json.go
- internal/encoder/compiler.go
- internal/encoder/context.go
- internal/encoder/encoder.go
- internal/encoder/opcode.go
- internal/encoder/option.go
- json.go
- option.go
-  `json.MarshalContext(context.Context, interface{}, ...json.EncodeOption) ([]byte, error)`
- `json.NewEncoder(io.Writer).EncodeContext(context.Context, interface{}, ...json.EncodeOption) error`
- `json.UnmarshalContext(context.Context, []byte, interface{}, ...json.DecodeOption) error`
- `json.NewDecoder(io.Reader).DecodeContext(context.Context, interface{}) error`
Then, if we implemented the following interface, callback it.
```go
type MarshalerContext interface {
MarshalJSON(context.Context) ([]byte, error)
}
type UnmarshalerContext interface {
UnmarshalJSON(context.Context, []byte) error
}
```
I thought there were situations in `MarshalJSON` and `UnmashalJSON` where I wanted to use `context.Context` .
For example, we consider the situation that in MarshalJSON, you want to access …
> Support context for MarshalJSON and UnmarshalJSON

- decode_test.go
- encode_test.go
- internal/decoder/array.go
> fix error when unmarshal empty array

- internal/decoder/map.go
Use `mapassign_faststr` to decode `map[string]XXX` type
> Improve performance of decoding map 

- internal/decoder/bytes.go
This is very similar to the fix here: https://github.com/goccy/go-json/commit/862884892441f97c34544557b3804e9b3061c7b1
Although the earlier fix applies for Unmarshal, it doesn't fix the case where a user uses NewDecoder(r).Decode(&res)
Here's a sample test that fails
```
package json
import (
"bytes"
"encoding/json"
"strings"
"testing"
goccy "github.com/goccy/go-json"
"github.com/stretchr/testify/assert"
)
type structure struct {
InnerBytes []byte `json:"inner_bytes"`
}
func Test_json_decode(t *testing.T) {
rawData := `{"inner_bytes":"bG93ZXI="}`
var resNative structure
var resGoccy structure
json.NewDecoder(bytes.NewBufferString(rawData)).Decode(&resNative)
goccy.NewDecoder(bytes.NewBufferString(rawData)).Decode(&resGoccy)
assert.Equal(t, []byte("lower"), resNative.InnerBytes) …
```
> Fix decoding of []byte type

- encode_test.go
- internal/encoder/compiler.go
- test/cover/cover_int_test.go
fix https://github.com/goccy/go-json/issues/263
> Fix encoding of indirect layout structure

- encode_test.go
- internal/cmd/generator/vm.go.tmpl
- internal/decoder/string.go
- internal/encoder/compiler.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/vm.go
Embed struct with tag does not have the key encoded, for example:
```go
type Foo struct {
Name string
}
type Bar struct {
Foo `json:"foo"`
ID  string `json:"id"`
}
func main() {
b := Bar{ID:"abc"}
v, err := json.Marshal(b)
if err != nil {
log.Fatal(err)
}
fmt.Println(string(v))
}
```
The output will be `{{"Name":""},"id":"abc"}`, the key of `foo` is lost, which is different from the behavior of `encoding/json`.
This PR will fix this issue.
> Fix encode issue for embed struct with tags

- decode_test.go
- internal/decoder/bytes.go
fix #266
This PR aim is same as #267
> Fix decoding of binary type with escaped char

- internal/decoder/slice.go
fix #275 ( also fix #268 )
If you decode using the same variable multiple times, the pointer from the previous decoding remains.
At this time, for example, the slice size is 32bytes in a 64-bit environment, so if library initialize only the start address with nil, the latter 24 bytes will remain with invalid values. To avoid this, I tried to initialize all fields by `typedmemmove` .
> Fix assign nil slice value

- decode_test.go
- internal/decoder/func.go
- internal/decoder/interface.go
- internal/decoder/number.go
- internal/decoder/string.go
- internal/decoder/struct.go
- internal/errors/error.go
resolve #274 
Change to an error message containing invalid character
> Improve error message

- encode_test.go
- internal/cmd/generator/vm.go.tmpl
- internal/encoder/opcode.go
- internal/encoder/vm/util.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/util.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/util.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/util.go
- internal/encoder/vm_indent/vm.go
Since empty interface type and not empty interface type are different layout of type, we have to consider about it .
fix https://github.com/goccy/go-json/issues/281
> Fix encoding of not empty interface type

- decode_test.go
- internal/decoder/map.go
fix #282
https://github.com/qyl2021/go-ugorji-go is corresponded similar problem .
This project says indirect element is decided by element size ( whether more than 128 bytes or not ), and only support map_fastxxx APIs at not indirect element case ( element size is 128 bytes or less  )
- https://github.com/qyl2021/go-ugorji-go/blob/5b6462b505850ae23ec0444474b85541c85514f6/codec/helper_unsafe_compiler_gc.go#L56-L87
- https://github.com/qyl2021/go-ugorji-go/blob/5b6462b505850ae23ec0444474b85541c85514f6/codec/helper_unsafe_compiler_gc.go#L34-L42
`maxKeySize` and` maxElemSize` are also defined in the latest source code.
https://github.com/golang/go/blob/7622e41c84fd9bb003a2d905b9f0545344842c3a/src/runtime/map.go#L74-L79
> Fix mapassign_faststr for indirect struct type

- encode_test.go
- internal/encoder/compiler.go
fix #285 
If encodes of empty struct value from interface type, go-json's compiler produces `OpStructHead - OpStructEnd - OpInterfaceEnd` operations. In this case, OpStructHead's next operation ( `OpStructEnd` ) 's index is equal `OpInterfaceEnd`'s index. So, when vm evaluated OpStructHead operation, stored value was overwritten.
Therefore, I fixed this behavior by added index number for `OpStructEnd` 's next operation .
> Fix encoding of empty struct interface type

- encode_test.go
- internal/encoder/compiler.go
- internal/encoder/opcode.go
> Fix embedded field conflict behavior

- internal/cmd/generator/vm.go.tmpl
- internal/encoder/vm/util.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/util.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/util.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/util.go
- internal/encoder/vm_indent/vm.go
Replace `appendNull` and `appendComma` with `appendNullComma`
```
b = appendNull(ctx, b)
b = appendComma(ctx, b)
```
```
b = appendNullComma(ctx, b)
```
> Refactor vm code for encoder

- internal/cmd/generator/vm.go.tmpl
- internal/encoder/encoder.go
- internal/encoder/map112.go
- internal/encoder/map113.go
- internal/encoder/opcode.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/vm.go
- size_test.go
Reuse mapIter object and use `runtime.mapiterinit` instead of `reflect.mapiterinit`
```
$ cd benchmarks && go test -bench Encode_MapInterface_GoJson
```
```
goos: darwin
goarch: amd64
pkg: benchmark
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Benchmark_Encode_MapInterface_GoJson-16          1504303               822.3 ns/op           144 B/op          2 allocs/op
```
```
$ cd benchmarks && go test -bench Encode_MapInterface_GoJson
```
```
goos: darwin
goarch: amd64
pkg: benchmark
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Benchmark_Encode_MapInterface_GoJson-16          1682722               694.4 ns/op            48 B/op          1 allocs/op
PASS
```
> Improve map encoding performance

- internal/encoder/decode_rune.go
- internal/encoder/string.go
Use optimized `utf8.DecodeRuneInString` for JSON encoding
> Optimize encoding path for escaped string

- README.md
- benchmarks/encode_test.go
- encode.go
- internal/cmd/generator/vm.go.tmpl
- internal/encoder/code.go
- internal/encoder/compiler.go
- internal/encoder/compiler_norace.go
- internal/encoder/compiler_race.go
- internal/encoder/encode_opcode_test.go
- internal/encoder/encoder.go
- internal/encoder/opcode.go
- internal/encoder/option.go
- internal/encoder/query.go
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/vm.go
- json.go
- query.go
- query_test.go
- size_test.go
- test/example/example_query_test.go
In encoding, you can dynamically filter the fields in the structure by creating a `json.FieldQuery`, adding it to `context.Context` using `json.SetFieldQueryToContext` and then passing it to `json.MarshalContext`.
This is a type-safe operation, so it is faster than filtering using `map[string]interface{}` .
When providing the REST API or GraphQL API, you may want to select and encode the fields of a structure.
In such a case, the conventional method requires to prepare a value of type `map[string]interface{}`, transfer the value of the selected field to map once, and then encode it.
This process is not only costly to create a map, but also a slow operation because you can't benefit from static typing.
So in go-json, if you creates `json.FieldQuery` that has information about selected …
> Supports dynamic filtering of struct fields

- benchmarks/decode_test.go
- benchmarks/large_payload.go
- internal/decoder/string.go
close #333 
```
name                                                        old time/op    new time/op    delta
_Decode_LargeSlice_EscapedString_GoJson-8                     38.8ms ± 1%     1.1ms ± 6%  -97.04%  (p=0.000 n=8+10)
```
```
name                                                        old time/op    new time/op    delta
_Decode_SmallStruct_Unmarshal_GoJson-8                         393ns ± 4%     399ns ± 1%     ~     (p=0.128 n=10+10)
_Decode_SmallStruct_Unmarshal_GoJsonNoEscape-8                 329ns ± 3%     340ns ± 6%   +3.34%  (p=0.008 n=9+9)
_Decode_SmallStruct_Stream_GoJson-8                            685ns ± 2%     680ns ± 3%     ~     (p=0.780 n=9+10)
_Decode_MediumStruct_Unmarshal_GoJson-8                       2.99µs ± 6%    3.07µs ± 5%   +2.80%  (p=0.035 n=10+9) …
```
> feat: improve performance when a payload contains escape sequence

- decode_test.go
- internal/decoder/string.go
fix #306 
```
name           old time/op  new time/op  delta
306/stdjson-8   314µs ± 0%   312µs ± 1%   -0.61%  (p=0.000 n=10+8)
306/go-json-8  3.36ms ± 1%  0.12ms ± 0%  -96.50%  (p=0.000 n=10+8)
```
> feat: improves escapeString's performance

- internal/encoder/compiler_norace.go
- internal/encoder/compiler_race.go
~This patch is a workaround of #350~
EDIT:
This was not a workaround, it is a solution.
fix #350
> fix: to safe when got unexpected typeptr

- decode_test.go
- internal/decoder/compile.go
fix #342
The map key decoder has an incompatible behavior when the type kind is string and the type has UnmarshalJSON.
> fix: an incompatible behavior on map key decoder

- encode.go
- encode_test.go
- internal/encoder/option.go
- internal/encoder/vm/debug_vm.go
- internal/encoder/vm_color/debug_vm.go
- internal/encoder/vm_color_indent/debug_vm.go
- internal/encoder/vm_indent/debug_vm.go
- option.go
> feat: add DebugWith option

- decode_test.go
- internal/encoder/opcode.go
> fix: to care about the case of OpInterfacePtr

- internal/encoder/compiler.go
fix #331
before:
```
18:47:08 | 200 |  6.702s |       127.0.0.1 | GET     | /api/nonuser/all/products
18:47:09 | 200 |     1ms |       127.0.0.1 | GET     | /api/nonuser/all/products
```
after:
```
00:58:50 | 200 |   137ms |       127.0.0.1 | GET     | /api/nonuser/all/products
00:59:00 | 200 |     1ms |       127.0.0.1 | GET     | /api/nonuser/all/products
```
> feat: improve performance on linkRecursiveCode

- internal/decoder/stream.go
- stream_test.go
Currently when using a decoder stream to read a Token at a time, it does not respect the `UseNumber` setting and unconditionally returns a `float64` instead. This fixes the stream handling to properly respect the `UseNumber` setting. Also adds a unit test for the case.
> fix stream tokenizing respecting UseNumber

- encode_test.go
- internal/cmd/generator/vm.go.tmpl
- internal/encoder/vm/vm.go
- internal/encoder/vm_color/vm.go
- internal/encoder/vm_color_indent/vm.go
- internal/encoder/vm_indent/vm.go
> fix: confusing nil in direct interface with typed nil

- decode_test.go
- internal/decoder/compile.go
> fix: support for embedding alias of primitive types

- encode_test.go
- internal/encoder/compiler.go
> fix: change isPtr to true on listElemCode

- encode_test.go
- internal/decoder/string.go
fix #374
io.MultiReaderなどを使うケースでReadをしてもio.EOFでなく要求したバイト数取得できないケースが存在する.
その際にfilledBufferがfalseになる. filledBufferがfalseの場合, bufferを拡張する処理が動かないため再利用の処理のみが実行される.
decodeUnicodeRuneの内部においてbufferが拡張される前提で書かれている処理があり, それが原因でpanicが発生していた.
新たに readAtLeast という関数を導入し, 期待するバッファーの状態を満たすようにした.
> fix: In decodeUnicode, the case that the expected buffer's state is not satisfied after reading.

- encode_test.go
- internal/decoder/compile.go
- internal/encoder/compiler.go
`typeptr == typeAddr.MaxTypeAddr` in this case, `cachedEncoder` get item out of range.
close #381
> fix encoder and decoder cache slice edge case

- decode_test.go
- internal/decoder/stream.go
fix https://github.com/goccy/go-json/issues/384
by increasing cursor by 1 to escape character properly.
> fix: unexpected behavior when buffer ends with backslash

- encode_test.go
- internal/encoder/compiler.go
should skip custom marshalling for map's key
> fix custom marshal for map's key

- Makefile
- benchmarks/path_test.go
- decode.go
- error.go
- internal/decoder/anonymous_field.go
- internal/decoder/array.go
- internal/decoder/assign.go
- internal/decoder/bool.go
- internal/decoder/bytes.go
- internal/decoder/float.go
- internal/decoder/func.go
- internal/decoder/int.go
- internal/decoder/interface.go
- internal/decoder/invalid.go
- internal/decoder/map.go
- internal/decoder/number.go
- internal/decoder/option.go
- internal/decoder/path.go
- internal/decoder/ptr.go
- internal/decoder/slice.go
- internal/decoder/string.go
- internal/decoder/struct.go
- internal/decoder/type.go
- internal/decoder/uint.go
- internal/decoder/unmarshal_json.go
- internal/decoder/unmarshal_text.go
- internal/decoder/wrapped_string.go
- internal/errors/error.go
- path.go
- path_test.go
Add a new API `json.CreatePath(string) (*json.Path, error)` .
`json.Path` type has some methods 
- Extract: extract json structure from input data
- Unmarshal: extract and decode from input data
- Get: extract and assign value from input value
> Support JSON Path for decoding

- decode.go
- internal/decoder/map.go
- internal/decoder/path.go
- internal/decoder/slice.go
- path.go
> Fix json path

- decode_test.go
- internal/decoder/array.go
fix #408 https://github.com/goccy/go-json/issues/414
> Fix checkptr error for array decoder

- encode_test.go
- internal/encoder/compiler.go
> fix: fixed handling of anonymous fields other than struct

- encode_test.go
- internal/encoder/vm_color_indent/util.go
- internal/encoder/vm_indent/util.go
fixed negative overflow on appendObjectEnd
fixed output on appendColon and appendObjectEnd
fix #417
> fix: fixed a problem that MarshalIndent does not work when UnorderedMap is specified

- decode_test.go
- internal/decoder/map.go
Current master breaks when encountering JSON containing an empty object containing whitespace like `{"obj":{ }}` when using the stream decoder - `Unmarshal()` behaves as expected.
This PR fixed that problem, and `NewDecoder().Decode()` will behave like `Unmarshal()`.
> Fix mapDecoder.DecodeStream() for empty objects containing whitespace

- encode_test.go
- internal/encoder/code.go
> fix: fixed an issue that could not set the correct NextField for fields in the embedded structure

- encode_test.go
- internal/encoder/code.go
> fix: fixed a problem with NextField being wrong when combining structure embedding and omitempty

- decode_test.go
- internal/decoder/ptr.go
> fix: decode struct with pointer must be nil

- internal/encoder/compact.go
the code below will panic
```
v := struct {
Type  string          `json:"type"`
Value json.RawMessage `json:"value"`
}{
Type:  "pure",
Value: json.RawMessage{0x22, 0x2e, 0xe2, 0x80, 0xa8, 0x22},
}
b, err := json.Marshal(&v)
fmt.Printf("b: %s, err: %v\n", string(b), err)
```
> fix: fix a bug for escaping 0xE2 0x80 0xA8 in compactString

- encode_test.go
- internal/encoder/encoder.go
@goccy, thank you very much for the library, it really improves performance a lot - **blazing fast!!!**
But I found incompatibility with the standard library (``encoding/json``) for Marshal []*time.Time (issue https://github.com/goccy/go-json/issues/523)
I have prepared a fix, I really hope for a prompt review my PR.
> Fix encode []*time.Time - check nil

- internal/runtime/type.go
fix #529 
- `runtime.AnalyzeTypeAddr()` writes to a global variable `alreadyAnalyzed`
- `runtime.AnalyzeTypeAddr()` could be called once each from both `initDecoder` and `initEncoder`
- When `initDecoder` and `initEncoder` were called simultaneously from different goroutines, it was detected as a data race, causing flaky test failures
Modified `runtime.AnalyzeTypeAddr` to use `sync.Once` instead of a global variable to ensure thread-safe initialization
Ran tests in my project using the following command:
```bash
go test -v -race ./... -count=1
```
Tests that were flaky in v0.10.4 now pass consistently with the fixed code
(verified with over 50 consecutive successful runs)
> fix: data race in AnalyzeTypeAddr for v0.10.4
